//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewaysTest.Domain.Common.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18n_Es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n_Es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GatewaysTest.Domain.Common.Language.I18n.Es", typeof(I18n_Es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway no encontrado.
        /// </summary>
        internal static string GatewayNotFound {
            get {
                return ResourceManager.GetString("GatewayNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Eliminado.
        /// </summary>
        internal static string GatewayRemoved {
            get {
                return ResourceManager.GetString("GatewayRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección Ip invalida.
        /// </summary>
        internal static string InvalidIpAddress {
            get {
                return ResourceManager.GetString("InvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre invalido.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Serie Invalido.
        /// </summary>
        internal static string InvalidSerialNo {
            get {
                return ResourceManager.GetString("InvalidSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral UID invalido .
        /// </summary>
        internal static string InvalidUid {
            get {
                return ResourceManager.GetString("InvalidUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor Invalido.
        /// </summary>
        internal static string InvalidVendor {
            get {
                return ResourceManager.GetString("InvalidVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se permiten 10 peripherals por gateway.
        /// </summary>
        internal static string OnlyTenPeripheralsByGateway {
            get {
                return ResourceManager.GetString("OnlyTenPeripheralsByGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral no encontrado.
        /// </summary>
        internal static string PeripheralNotFound {
            get {
                return ResourceManager.GetString("PeripheralNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peripheral Eliminado.
        /// </summary>
        internal static string PeripheralRemoved {
            get {
                return ResourceManager.GetString("PeripheralRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de serie ya existe.
        /// </summary>
        internal static string SerialNoAlreadyExist {
            get {
                return ResourceManager.GetString("SerialNoAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido.
        /// </summary>
        internal static string UnknowError {
            get {
                return ResourceManager.GetString("UnknowError", resourceCulture);
            }
        }
    }
}
